# Generated by Django 5.1.7 on 2025-06-16 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDARate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(max_length=10)),
                ('da_rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_hour_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CountryDASetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(max_length=10)),
                ('da_rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_hour_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Country DA Rate Setting',
                'verbose_name_plural': 'Country DA Rate Settings',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='DailyAllowanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeExpenseGrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeExpenseSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_period_days', models.PositiveIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kilometers', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expense_receipts/')),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Forwarded to Manager', 'Forwarded to Manager'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('final_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('accountant_remark', models.TextField(blank=True, null=True)),
                ('manager_remark', models.TextField(blank=True, null=True)),
                ('forwarded_to_manager', models.BooleanField(default=False)),
                ('reviewed_by_manager', models.BooleanField(default=False)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('requires_kilometers', models.BooleanField(default=False)),
                ('requires_receipt', models.BooleanField(default=False)),
                ('rate_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalDASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_da', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('domestic_da', models.DecimalField(decimal_places=2, default=350, max_digits=10)),
                ('international_da', models.DecimalField(decimal_places=2, default=800, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalExpenseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_grace_days', models.PositiveIntegerField(default=10, help_text='Allowed days to submit backdated expenses.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('da_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('is_extended', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('forwarded_to_accountant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile')),
            ],
        ),
    ]
