# Generated by Django 5.1.7 on 2025-08-30 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_deducted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryDARate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(max_length=10)),
                ('da_rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_hour_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CountryDASetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(max_length=10)),
                ('da_rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_hour_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Country DA Rate Setting',
                'verbose_name_plural': 'Country DA Rate Settings',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='DailyAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('da_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('is_extended', models.BooleanField(default=False)),
                ('is_weekend', models.BooleanField(default=False)),
                ('auto_generated', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('TIMESHEET', 'Timesheet'), ('WEEKEND', 'Weekend entitlement'), ('EXTRA_HOURS', 'Extra hours'), ('MANUAL', 'Manual')], default='TIMESHEET', max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('reimbursed', models.BooleanField(default=False)),
                ('forwarded_to_accountant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forwarded_to_accountmanager', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('settlement_method', models.CharField(blank=True, choices=[('ADVANCE', 'Advance'), ('CASH', 'Cash')], max_length=20, null=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('settled_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyAllowanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAllowanceSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('ADVANCE', 'Adjusted Against Advance'), ('CASH', 'Cash/Bank Reimbursement')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeExpenseGrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeExpenseSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_period_days', models.PositiveIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(blank=True, choices=[('ACCOUNTANT', 'Accountant'), ('MANAGER', 'Manager'), ('ACCOUNT_MANAGER', 'Account Manager'), ('APPROVED', 'Approved'), ('SETTLED', 'Settled'), ('REJECTED', 'Rejected')], default='ACCOUNTANT', max_length=20)),
                ('date', models.DateField()),
                ('kilometers', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expense_receipts/')),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Forwarded to Manager', 'Forwarded to Manager'), ('Forwarded to Account Manager', 'Forwarded to Account Manager'), ('Approved', 'Approved'), ('Settled', 'Settled'), ('Rejected', 'Rejected')], default='Submitted', max_length=50)),
                ('reimbursed', models.BooleanField(default=False)),
                ('accountant_remark', models.TextField(blank=True, null=True)),
                ('manager_remark', models.TextField(blank=True, null=True)),
                ('forwarded_to_manager', models.BooleanField(default=False)),
                ('reviewed_by_manager', models.BooleanField(default=False)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forwarded_to_accountmanager', models.BooleanField(default=False)),
                ('from_location', models.CharField(blank=True, max_length=100, null=True)),
                ('to_location', models.CharField(blank=True, max_length=100, null=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'permissions': [('can_settle', 'Can settle expenses')],
            },
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('requires_kilometers', models.BooleanField(default=False)),
                ('requires_receipt', models.BooleanField(default=False)),
                ('rate_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_amount_allowed', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum reimbursable amount for this expense type', max_digits=10, null=True)),
                ('requires_travel_locations', models.BooleanField(default=False)),
                ('requires_cooldown', models.BooleanField(default=False)),
                ('cooldown_days', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalDASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_da', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('domestic_da', models.DecimalField(decimal_places=2, default=350, max_digits=10)),
                ('international_da', models.DecimalField(decimal_places=2, default=800, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalExpenseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_grace_days', models.PositiveIntegerField(default=10, help_text='Allowed days to submit backdated expenses.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjusted_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Final amount after adjusting for previous negative balances', max_digits=10, null=True)),
                ('purpose', models.TextField()),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('approved_by_manager', models.BooleanField(default=False)),
                ('approved_by_accountant', models.BooleanField(default=False)),
                ('settled_by_account_manager', models.BooleanField(default=False)),
                ('date_approved_by_accountant', models.DateTimeField(blank=True, null=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Forwarded to Manager', 'Forwarded to Manager'), ('Forwarded to Accountant', 'Forwarded to Accountant'), ('Forwarded to Account Manager', 'Forwarded to Account Manager'), ('Settled', 'Settled'), ('Rejected', 'Rejected')], default='Submitted', max_length=50)),
                ('current_stage', models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant'), ('ACCOUNT_MANAGER', 'Account Manager'), ('SETTLED', 'Settled'), ('REJECTED', 'Rejected')], default='MANAGER', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile')),
            ],
        ),
    ]
