# Generated by Django 5.1.7 on 2025-04-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_accountant_remark_expense_manager_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='final_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='forwarded_to_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='manager_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='reviewed_by_manager',
            field=models.BooleanField(default=False),
        ),
    ]
