# Generated by Django 5.1.7 on 2025-06-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyallowance',
            name='reimbursed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='reimbursed',
            field=models.BooleanField(default=False),
        ),
    ]
