# Generated by Django 5.1.7 on 2025-09-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='timesheet_required',
            field=models.BooleanField(default=False, help_text='Require timesheet for expenses of this type'),
        ),
    ]
