# Generated by Django 5.1.7 on 2025-06-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_dailyallowance_reimbursed_expense_reimbursed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyallowance',
            name='forwarded_to_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='forwarded_to_director',
            field=models.BooleanField(default=False),
        ),
    ]
