# Generated by Django 5.1.7 on 2025-06-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_dailyallowance_forwarded_to_director_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyallowance',
            old_name='forwarded_to_director',
            new_name='forwarded_to_accountmanager',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='forwarded_to_director',
            new_name='forwarded_to_accountmanager',
        ),
    ]
