# Generated by Django 5.1.7 on 2025-06-27 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeeprofile_role'),
        ('expenses', '0005_rename_forwarded_to_director_dailyallowance_forwarded_to_accountmanager_and_more'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.TextField()),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('approved_by_manager', models.BooleanField(default=False)),
                ('approved_by_accountant', models.BooleanField(default=False)),
                ('settled_by_account_manager', models.BooleanField(default=False)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
