# Generated by Django 5.1.7 on 2025-05-06 06:49

from django.db import migrations

def migrate_expense_types(apps, schema_editor):
    Expense = apps.get_model('expenses', 'Expense')
    ExpenseType = apps.get_model('expenses', 'ExpenseType')

    for expense in Expense.objects.all():
        if not expense.new_expense_type and expense.expense_type:
            try:
                # Try to find a matching ExpenseType by name
                etype = ExpenseType.objects.get(name__iexact=expense.expense_type)
                expense.new_expense_type = etype
                expense.save()
            except ExpenseType.DoesNotExist:
                continue  # Skip if no match found

class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_employeeexpensesetting'),  # Replace with actual previous migration name
    ]

    operations = [
        migrations.RunPython(migrate_expense_types),
    ]
