# Generated by Django 5.1.7 on 2025-06-27 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_advancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='advance_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_expenses', to='expenses.advancerequest'),
        ),
    ]
