# Generated by Django 5.1.7 on 2025-05-07 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_leavebalance_updated_at'),
        ('expenses', '0006_auto_20250506_1219'),
        ('project', '0007_alter_project_location'),
        ('timesheet', '0003_timesheet_da_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_type',
        ),
        migrations.CreateModel(
            name='DailyAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('da_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('is_extended', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('forwarded_to_accountant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('timesheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timesheet.timesheet')),
            ],
        ),
    ]
