# Generated by Django 5.1.7 on 2025-06-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_advancerequest_balance_expense_advance_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='date_approved_by_accountant',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
