# Generated by Django 5.1.7 on 2025-05-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_remove_expense_expense_type_dailyallowance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDARate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(max_length=10)),
                ('da_rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_hour_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CountryDASetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(help_text='Currency code like INR, USD, EUR etc.', max_length=10)),
                ('da_rate_per_hour', models.DecimalField(decimal_places=2, help_text='DA Rate for regular working hours per hour', max_digits=10)),
                ('extra_hour_rate', models.DecimalField(decimal_places=2, help_text='DA Rate for extra working hours per hour', max_digits=10)),
            ],
            options={
                'verbose_name': 'Country DA Rate Setting',
                'verbose_name_plural': 'Country DA Rate Settings',
                'ordering': ['country'],
            },
        ),
    ]
