# Generated by Django 5.1.7 on 2025-07-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_advancerequest_date_approved_by_accountant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancerequest',
            name='balance',
        ),
    ]
