# Generated by Django 5.1.7 on 2025-07-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_advanceadjustmentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='adjusted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final amount after adjusting for previous negative balances', max_digits=10, null=True),
        ),
    ]
