# Generated by Django 5.1.7 on 2025-07-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_advancerequest_adjusted_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='max_amount_allowed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum reimbursable amount for this expense type', max_digits=10, null=True),
        ),
    ]
