# Generated by Django 5.1.7 on 2025-07-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_expensetype_max_amount_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='requires_travel_locations',
            field=models.BooleanField(default=False),
        ),
    ]
