# Generated by Django 5.1.7 on 2025-07-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_expensetype_requires_travel_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='from_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='to_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
