# Generated by Django 5.1.7 on 2025-07-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_expense_from_location_expense_to_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='cooldown_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='requires_cooldown',
            field=models.BooleanField(default=False),
        ),
    ]
