# Generated by Django 5.1.7 on 2025-07-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_expensetype_cooldown_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Forwarded to Manager', 'Forwarded to Manager'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Forwarded to AccountManager', 'Forwarded to AccountManager')], default='Pending', max_length=30),
        ),
    ]
