# Generated by Django 5.1.7 on 2025-07-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_alter_expense_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='final_status',
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Forwarded to Manager', 'Forwarded to Manager'), ('Forwarded to Account Manager', 'Forwarded to Account Manager'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=50),
        ),
    ]
