# Generated by Django 5.1.7 on 2025-08-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_remove_expense_final_status_alter_expense_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Forwarded to Manager', 'Forwarded to Manager'), ('Forwarded to Accountant', 'Forwarded to Accountant'), ('Forwarded to Account Manager', 'Forwarded to Account Manager'), ('Settled', 'Settled'), ('Rejected', 'Rejected')], default='Submitted', max_length=50),
        ),
    ]
