# Generated by Django 5.1.7 on 2025-08-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_advancerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='current_stage',
            field=models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant'), ('ACCOUNT_MANAGER', 'Account Manager'), ('SETTLED', 'Settled'), ('REJECTED', 'Rejected')], default='MANAGER', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='current_stage',
            field=models.CharField(blank=True, choices=[('ACCOUNTANT', 'Accountant'), ('MANAGER', 'Manager'), ('ACCOUNT_MANAGER', 'Account Manager'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='ACCOUNTANT', max_length=20),
        ),
    ]
