# Generated by Django 5.1.7 on 2025-08-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_advancerequest_current_stage_expense_current_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='current_stage',
            field=models.CharField(blank=True, choices=[('ACCOUNTANT', 'Accountant'), ('MANAGER', 'Manager'), ('ACCOUNT_MANAGER', 'Account Manager'), ('APPROVED', 'Approved'), ('SETTLED', 'Settled'), ('REJECTED', 'Rejected')], default='ACCOUNTANT', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Forwarded to Manager', 'Forwarded to Manager'), ('Forwarded to Account Manager', 'Forwarded to Account Manager'), ('Approved', 'Approved'), ('Settled', 'Settled'), ('Rejected', 'Rejected')], default='Submitted', max_length=50),
        ),
    ]
