# Generated by Django 5.1.7 on 2025-08-19 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeeprofile_role'),
        ('expenses', '0020_alter_expense_current_stage_alter_expense_status'),
        ('project', '0001_initial'),
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyallowance',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='dailyallowance',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyallowance',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyallowance',
            name='source',
            field=models.CharField(choices=[('TIMESHEET', 'Timesheet'), ('WEEKEND', 'Weekend entitlement'), ('EXTRA_HOURS', 'Extra hours'), ('MANUAL', 'Manual')], default='TIMESHEET', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyallowance',
            name='timesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_allowances', to='timesheet.timesheet'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyallowance',
            unique_together={('employee', 'project', 'date')},
        ),
    ]
