# Generated by Django 5.1.7 on 2025-08-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021_alter_dailyallowance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyallowance',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
