# Generated by Django 5.1.7 on 2025-08-20 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0022_dailyallowance_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceadjustmentlog',
            name='da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.dailyallowance'),
        ),
        migrations.AddField(
            model_name='dailyallowance',
            name='settled_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailyallowance',
            name='settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyallowance',
            name='settlement_method',
            field=models.CharField(blank=True, choices=[('ADVANCE', 'Advance'), ('CASH', 'Cash')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dailyallowance',
            name='settlement_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='da_settlements', to='expenses.advancerequest'),
        ),
        migrations.AlterField(
            model_name='advanceadjustmentlog',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.expense'),
        ),
    ]
