# Generated by Django 5.1.7 on 2025-08-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0024_alter_dailyallowance_settlement_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
