# Generated by Django 5.1.7 on 2025-04-15 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR'), ('Accountant', 'Accountant'), ('Director', 'Director'), ('Admin', 'Admin')], default='Employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employeeprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
