# Generated by Django 5.1.7 on 2025-06-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR'), ('Accountant', 'Accountant'), ('Director', 'Director'), ('Admin', 'Admin'), ('Account Manager', 'Account Manager')], default='Employee', max_length=20),
        ),
    ]
