# Generated by Django 5.1.7 on 2025-04-28 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeeprofile_role_and_more'),
        ('project', '0004_project_da_rate_project_extra_hour_da_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.task'),
        ),
    ]
