# Generated by Django 5.1.7 on 2025-05-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimesheetEntry',
        ),
    ]
