# Generated by Django 5.1.7 on 2025-05-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_timesheetentry_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='grace_period_days',
            field=models.IntegerField(default=0),
        ),
    ]
