# Generated by Django 5.1.7 on 2025-05-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_delete_timesheetentry'),
        ('project', '0002_project_daily_rate_project_type_alter_project_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='projects',
            field=models.ManyToManyField(related_name='employees', to='project.project'),
        ),
    ]
