# Generated by Django 5.1.7 on 2025-05-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employeeprofile_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='projects',
        ),
    ]
