# Generated by Django 5.1.7 on 2025-05-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_leavebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
