# Generated by Django 5.1.7 on 2025-05-16 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('task_description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('da_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_allowance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_allowance_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='employee.employeeprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.task')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Half Day', 'Half Day'), ('Absent', 'Absent')], max_length=20)),
                ('added_c_off', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
