# Generated by Django 5.1.11 on 2025-09-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="worked_onsite",
            field=models.BooleanField(
                blank=True,
                help_text="Indicates whether this slot was worked onsite. Leave blank to use the project's default.",
                null=True,
            ),
        ),
    ]