# Generated by Django 5.1.7 on 2025-05-07 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_leavebalance'),
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='da_rate',
            new_name='daily_allowance_amount',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='daily_allowance_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Half Day', 'Half Day'), ('Absent', 'Absent')], max_length=20)),
                ('added_c_off', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
