# Generated by Django 5.1.7 on 2025-05-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_timesheetentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='is_billable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
