# Generated by Django 5.1.7 on 2025-05-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_rename_da_rate_timesheet_daily_allowance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='da_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
