# Generated by Django 5.1.7 on 2025-05-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_timesheet_is_billable_timesheet_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='is_draft',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='is_billable',
            field=models.BooleanField(default=False),
        ),
    ]
