# Generated by Django 5.1.7 on 2025-05-28 07:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_employeeprofile_projects'),
        ('timesheet', '0004_remove_timesheet_is_draft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensatoryOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_earned', models.DateField()),
                ('hours_logged', models.DecimalField(decimal_places=2, max_digits=4)),
                ('approved', models.BooleanField(default=False)),
                ('credited_days', models.DecimalField(decimal_places=1, max_digits=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile')),
                ('timesheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timesheet.timesheet')),
            ],
        ),
        migrations.CreateModel(
            name='CompOffApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField(default=django.utils.timezone.now)),
                ('compoff_date', models.DateField()),
                ('days_requested', models.DecimalField(decimal_places=1, max_digits=3)),
                ('approved', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CompOffBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile')),
            ],
        ),
    ]
