# Generated by Django 5.1.7 on 2025-05-28 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_compensatoryoff_compoffapplication_compoffbalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compoffapplication',
            old_name='compoff_date',
            new_name='date_applied_for',
        ),
        migrations.RenameField(
            model_name='compoffapplication',
            old_name='days_requested',
            new_name='number_of_days',
        ),
        migrations.RemoveField(
            model_name='compoffapplication',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='compoffapplication',
            name='date_applied',
        ),
        migrations.RemoveField(
            model_name='compoffapplication',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='compoffapplication',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compoffapplication',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compoffapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
