# Generated by Django 5.1.7 on 2025-05-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0006_rename_compoff_date_compoffapplication_date_applied_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TimesheetEntry',
        ),
    ]
