# Generated by Django 5.1.7 on 2025-06-01 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_daily_rate_project_type_alter_project_budget'),
        ('timesheet', '0007_timesheet_rejected_at_timesheet_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='time_from',
            new_name='shift_end',
        ),
        migrations.RenameField(
            model_name='timesheet',
            old_name='time_to',
            new_name='shift_start',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='project',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='task',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='task_description',
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('description', models.TextField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.task')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='timesheet.timesheet')),
            ],
            options={
                'ordering': ['time_from'],
            },
        ),
    ]
