# Generated by Django 5.1.7 on 2025-06-02 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_daily_rate_project_type_alter_project_budget'),
        ('timesheet', '0008_rename_time_from_timesheet_shift_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
