# Generated by Django 5.1.7 on 2025-06-03 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_employeeprofile_projects'),
        ('timesheet', '0009_alter_timeslot_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='employee.employeeprofile'),
        ),
    ]
