# Generated by Django 5.1.7 on 2025-06-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0010_timeslot_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
