# Generated by Django 5.1.7 on 2025-04-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250415_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('manage_employees', 'Can manage employee roles'), ('manage_managers', 'Can manage manager roles'), ('manage_hr', 'Can manage HR roles')]},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
