# Generated by Django 5.1.7 on 2025-05-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('Generic', 'Generic'), ('Salary_Revision', 'Salary Revision'), ('Offer_Letter', 'Offer Letter'), ('Cover_Letter', 'Cover Letter')], default='Generic', max_length=50),
        ),
    ]
