# Generated by Django 5.1.7 on 2025-05-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0002_documenttemplate_template_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='template_type',
        ),
    ]
