# Generated by Django 5.1.7 on 2025-06-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DASetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_hours', models.IntegerField(default=6)),
                ('da_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.locationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('rate_type', models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily')], max_length=10, null=True, verbose_name='Billing Method')),
                ('rate_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Charge Rate to Customer')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Total budget allocated for Turnkey projects. Used for tracking expenses and DA.', max_digits=12, null=True)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Employee Daily Rate')),
                ('da_type', models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily')], max_length=10, null=True, verbose_name='DA Type (Daily/Hourly)')),
                ('da_rate_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DA Rate (per Hour/Day)')),
                ('extended_hours_threshold', models.IntegerField(blank=True, null=True, verbose_name='Extra Hours Threshold (Weekly)')),
                ('extended_hours_da_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DA Rate for Extra Hours')),
                ('off_day_da_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weekend Off-Day DA')),
                ('location_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.locationtype', verbose_name='Project Location')),
                ('status_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectstatus', verbose_name='Project Status')),
                ('project_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projecttype', verbose_name='Project Type')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExpensePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_transport', models.BooleanField(default=True)),
                ('allow_accommodation', models.BooleanField(default=False)),
                ('allow_safety_shoes', models.BooleanField(default=False)),
                ('safety_shoe_tracker_days', models.PositiveIntegerField(default=365)),
                ('mobile_recharge_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('domestic_transport_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('international_transport_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.mainskill')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='project.project')),
                ('subskill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.subskill')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='project.task')),
            ],
        ),
    ]
