# Generated by Django 5.1.7 on 2025-04-15 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('Turnkey', 'Turnkey'), ('Service', 'Service')], max_length=20)),
                ('billing_method', models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily')], max_length=20)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('daily_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('location', models.CharField(choices=[('Local', 'Local'), ('Domestic', 'Domestic'), ('International', 'International')], max_length=20)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('da_rate_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_hour_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=20)),
                ('documents', models.FileField(blank=True, null=True, upload_to='project_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExpensePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_transport', models.BooleanField(default=True)),
                ('allow_accommodation', models.BooleanField(default=False)),
                ('allow_safety_shoes', models.BooleanField(default=False)),
                ('safety_shoe_tracker_days', models.PositiveIntegerField(default=365)),
                ('mobile_recharge_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('domestic_transport_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('international_transport_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('progress', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='project.task')),
            ],
        ),
    ]
