# Generated by Django 5.1.7 on 2025-08-30 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequiredskill',
            name='main_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_requirements', to='skills.mainskill'),
        ),
        migrations.AddField(
            model_name='projectrequiredskill',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='project.project'),
        ),
        migrations.AddField(
            model_name='projectrequiredskill',
            name='subskill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_requirements', to='skills.subskill'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectstatus', verbose_name='Project Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projecttype', verbose_name='Project Type'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='project.task'),
        ),
    ]
