# Generated by Django 5.1.7 on 2025-05-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Turnkey', 'Turnkey (Fixed Budget & Duration)'), ('Service', 'Service (Daily Rate Billing)')], default='Turnkey', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
