# Generated by Django 5.1.7 on 2025-04-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, unique=True)),
                ('currency_code', models.CharField(max_length=10)),
                ('da_rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_hour_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
