# Generated by Django 5.1.7 on 2025-06-08 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_daily_rate_project_type_alter_project_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AddField(
            model_name='project',
            name='project_documents',
            field=models.FileField(blank=True, null=True, upload_to='project_docs/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='da_rate_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DA Rate per Hour'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.locationtype', verbose_name='Project Location'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projecttype', verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily')], max_length=10, null=True, verbose_name='Billing Method'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectstatus', verbose_name='Project Status'),
        ),
    ]
