# Generated by Django 5.1.7 on 2025-04-15 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_countrydasettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryDASettings',
            new_name='CountryDARate',
        ),
        migrations.RenameField(
            model_name='countrydarate',
            old_name='country_name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='countrydarate',
            old_name='currency_code',
            new_name='currency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='country',
        ),
        migrations.RemoveField(
            model_name='project',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='da_rate_per_hour',
        ),
        migrations.RemoveField(
            model_name='project',
            name='extra_hour_rate',
        ),
        migrations.AddField(
            model_name='project',
            name='country_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.countrydarate'),
        ),
    ]
