# Generated by Django 5.1.7 on 2025-04-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_countrydasettings_countrydarate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='da_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='extra_hour_da_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='skills_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='billing_method',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily')], max_length=20, null=True, verbose_name='Billing Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Turnkey', 'Turnkey'), ('Service', 'Service')], max_length=20, null=True),
        ),
    ]
