# Generated by Django 5.1.7 on 2025-06-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_type_project_project_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
