# Generated by Django 5.1.7 on 2025-09-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_seed_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_onsite',
            field=models.BooleanField(default=False, verbose_name='Employee onsite'),
        ),
    ]
