# Generated by Django 5.1.7 on 2025-04-28 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_skillassignment'),
        ('project', '0004_project_da_rate_project_extra_hour_da_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.mainskill')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='project.project')),
                ('subskill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.subskill')),
            ],
        ),
    ]
