# Generated by Django 5.1.11 on 2025-09-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_project_is_onsite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmaterial",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectmaterial",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]