# Generated by Django 5.1.7 on 2025-06-09 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_location_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='da_rate_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.locationtype', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily')], max_length=10, null=True),
        ),
    ]
