# Generated by Django 5.1.7 on 2025-06-09 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_da_rate_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_documents',
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Turnkey', 'Turnkey (Fixed Budget & Duration)'), ('Service', 'Service (Daily Rate Billing)')], default='Turnkey', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.locationtype'),
        ),
    ]
