# Generated by Django 5.1.7 on 2025-05-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_task_end_date_task_is_completed_task_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(choices=[('Local', 'Local'), ('Domestic', 'Domestic'), ('International', 'International'), ('Office', 'Office')], max_length=20),
        ),
    ]
