# Generated by Django 5.1.7 on 2025-05-09 11:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_countrydarate_countrydasetting'),
        ('project', '0007_alter_project_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='country_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.countrydarate'),
        ),
        migrations.RemoveField(
            model_name='projectexpensepolicy',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='daily_hourly_rate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills_required',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_extra_hour_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_regular_hour_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='employee_max_hours_per_week',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='project',
            name='employee_regular_hours_per_day',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='project',
            name='billing_method',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='da_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DA Rate / Hour'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='extra_hour_da_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Extra Hour DA Rate / Hour'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Turnkey', 'Turnkey'), ('Service', 'Service')], default='Turnkey', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='CountryDARate',
        ),
        migrations.DeleteModel(
            name='ProjectExpensePolicy',
        ),
    ]
