# Generated by Django 5.1.7 on 2025-06-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_project_type_alter_project_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='da_rate_per_day',
        ),
        migrations.AddField(
            model_name='project',
            name='da_rate_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DA Rate (per Hour/Day)'),
        ),
        migrations.AddField(
            model_name='project',
            name='da_type',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily')], max_length=10, null=True, verbose_name='DA Type (Daily/Hourly)'),
        ),
        migrations.AddField(
            model_name='project',
            name='off_day_da_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weekend Off-Day DA'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Employee Daily Rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='extended_hours_da_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DA Rate for Extra Hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='extended_hours_threshold',
            field=models.IntegerField(blank=True, null=True, verbose_name='Extra Hours Threshold (Weekly)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily')], max_length=10, null=True, verbose_name='Billing Method'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rate_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Charge Rate to Customer'),
        ),
    ]
