# Generated by Django 5.1.7 on 2025-05-13 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_project_country_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDARate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(max_length=10)),
                ('da_rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_hour_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer_extra_hour_rate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer_regular_hour_rate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='employee_max_hours_per_week',
        ),
        migrations.RemoveField(
            model_name='project',
            name='employee_regular_hours_per_day',
        ),
        migrations.AddField(
            model_name='project',
            name='daily_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='skills_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='billing_method',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily')], max_length=20, null=True, verbose_name='Billing Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='da_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='extra_hour_da_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(choices=[('Local', 'Local'), ('Domestic', 'Domestic'), ('International', 'International')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Turnkey', 'Turnkey'), ('Service', 'Service')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='country_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.countrydarate'),
        ),
        migrations.CreateModel(
            name='ProjectExpensePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_transport', models.BooleanField(default=True)),
                ('allow_accommodation', models.BooleanField(default=False)),
                ('allow_safety_shoes', models.BooleanField(default=False)),
                ('safety_shoe_tracker_days', models.PositiveIntegerField(default=365)),
                ('mobile_recharge_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('domestic_transport_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('international_transport_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
