# Generated by Django 5.1.7 on 2025-06-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_project_da_rate_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total budget allocated for Turnkey projects. Used for tracking expenses and DA.', max_digits=12, null=True),
        ),
    ]
