# Generated by Django 5.1.7 on 2025-09-17 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skillquestion_employeeanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillquestion',
            name='subskill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='skills.subskill'),
        ),
    ]
