# Generated by Django 5.1.7 on 2025-09-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skillquestion_subskill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillquestion',
            options={'ordering': ('main_skill', 'subskill', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='skillquestion',
            unique_together={('main_skill', 'subskill', 'order')},
        ),
    ]
