# Generated by Django 5.1.7 on 2025-09-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_backfill_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainskill',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
