# Generated by Django 5.1.7 on 2025-09-20 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_skillquestion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SkillMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='employeeskill',
            options={'ordering': ('employee', 'main_skill__name', 'subskill__name')},
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='certification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='proficiency',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0-100 (preferred) — new standardized field', null=True),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='years_experience',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='mainskill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_skills', to='skills.skillcategory'),
        ),
        migrations.CreateModel(
            name='SkillMatrixRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_proficiency', models.PositiveSmallIntegerField(default=50)),
                ('mandatory', models.BooleanField(default=False)),
                ('main_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skills.mainskill')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='skills.skillmatrix')),
                ('subskill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skills.subskill')),
            ],
            options={
                'ordering': ('matrix__name', 'main_skill__name', 'subskill__name'),
                'unique_together': {('matrix', 'main_skill', 'subskill')},
            },
        ),
    ]
