# Generated by Django 5.1.7 on 2025-09-08 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ends_flow', models.BooleanField(default=False, help_text='If checked, performing this action typically ends the approval instance (e.g. approve/reject).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Approval Action Type',
                'verbose_name_plural': 'Approval Action Types',
            },
        ),
        migrations.AlterModelOptions(
            name='approvalaction',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='action_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='approvals.approvalactiontype'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='allowed_actions',
            field=models.ManyToManyField(blank=True, to='approvals.approvalactiontype'),
        ),
    ]
